### ISSUE TITLE
No module error

### ISSUE THREAD

**Issue by mab-is-fun** [neuronsimulator/pythontutorial#4]
">>> import neuron
Found NEURON at C:\Python27\neuronhome
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\neuron\__init__.py", line 117, in <module>
    import neuron.hoc
ImportError: No module named hoc"

I'm not able to set up the NEURON package. It is throwing the above error. Kindly suggest a fix to this.
Thanks in advance.

**Comment by ramcdougal** [comment]
This is a PATH or PYTHONPATH issue.

There shouldn't be anything from NEURON inside site-packages on windows. (On Linux and Mac, you can just use pip to get the development version but this isn't supported for windows yet.)

The simplest fix is to go back to NEURON.yale.edu, redownload, and reinstall.

When you do, there's an option to set the relevant paths. By default it should be checked, but double check. It'll set the following in your PATH:

    c:\nrn\bin
    c:\nrn\mingw\usr\bin

I'm not sure what it sets in PYTHONPATH but it should include somewhere in C:\nrn

You'll have to open a new terminal for there changes to PATH etc to take effect.

While NEURON continues to support Python 2.7 for the time being, be aware that version of Python is a decade old and no longer receiving security updates or bug fixes. The current version of Python is 3.8.

**Comment by mab-is-fun** [comment]
Thank you for your email. I've tried using both the versions of python and
'Module not found' error persisted, which is why I installed the nrn
package in the pythonpath. I'll try reinstalling the NEURON and get back to
you.
Thanks and regards
*Manoj A B*
*BTech 3rd Year*
*National Institute of Technology Karnataka,*
*Surathkal. *
